### ISSUE TITLE
Crash In HomeActivity

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#319] opened 2019-07-01 14:57 UTC
**Describe the feature you'd like**
Wrong state class, expecting View State but received class androidx.viewpager.widget.ViewPager$i instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/0x8. Make sure other views do not use the same id.

**Comment by adityastic** [comment] 2019-07-01 15:04
Duplicate of #316. Please close

**Closed** 2019-07-01 16:08 UTC
Labels: BOSS, BOUNTY 100
